name = "cf-api"
main = "index.js"
compatibility_date = "2024-09-23"

[vars]
JWT_SECRET     = "ganti-dengan-secret-panjang-dan-kuat"
ALLOWED_TABLES = "users,products,orders,courses,enrollments,progress"
ADMIN_USER     = "admin"
ADMIN_PASS     = "rahasia123"

# OAuth Client ID dari Google Cloud Console (Credentials → OAuth 2.0 Client ID → Web application)
GOOGLE_CLIENT_ID   = "657734502201-3nashfia0j8u3p1lu1n3tpl3tk22p8om.apps.googleusercontent.com"

# Whitelist email → role otomatis saat login Google pertama kali (pisahkan koma)
ADMIN_EMAILS       = "wawan@sismadi.com"
INSTRUCTOR_EMAILS  = "instruktur1@example.com,instruktur2@example.com"

[[d1_databases]]
binding      = "DB"
database_name = "pkm-db-lms"
database_id   = "8a28cff3-9b5d-454c-9f5e-e333d37a681d"
